# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ccd93dc81980553a61adc8182b0d982b6524611c58ed20cf84f44633ed4c0c2373bfde61279cb63623796c7d58c935c1454af76a0d01bb842ae68394af14459

test:
  secret_key_base: 7cd6be57e5a3dff8d0d56f63434e75ecb40afd4a17ea9d9b6effd302bbd89cc554367ea33716f51b577c6f58014d162ae497b36ac3630dbf8ad12f640ec3278d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
